name: Upload Python Package

on:
  workflow_run:
    workflows: ["run-tests"]
    types: [ completed ]
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build twine

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Inspect wheel METADATA
        run: |
          echo ">>> METADATA in dist/aynse-*.whl:"
          unzip -p dist/aynse-*py3-none-any.whl '*.dist-info/METADATA' | head -20
          echo ">>> end METADATA"

      - name: Verify distributions
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
